# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170714_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakibburl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
