# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170716_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakibburl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
